name: ci
on:
  push:
jobs:
  build-OdinSnap:
    name: build OdinSnap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.20.0
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Build
        run: |
          yarn build
  build-vite:
    name: build react vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.20.0
      - name: Install dependencies
        working-directory: ./examples/react-vite/
        run: yarn install
      - name: Build
        run: |
          cd examples/react-vite/
          yarn build
  build-webpack-eg:
    name: build react webpack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.20.0
      - name: Install dependencies
        working-directory: ./examples/react-webpack/
        run: yarn install
      - name: Build
        run: |
          cd examples/react-webpack/
          yarn build
