name: lint
on:
  push:
jobs:
  build:
    name: lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22.20.0
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: lint checks
        run: |
          yarn lint
